language: node_js

node_js:
  - "node"
  - "lts"
  - "8"

cache:
  - npm
  - yarn

jobs:
  include:
    - stage: lint
      node_js: "node"
      script: npm run lint

    - stage: coverage
      node_js: "node"
      script: npm run coveralls
      if: branch = master

    - stage: release
      node_js: "node"
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true

notifications:
  email: false
  webhooks:
    urls:
      - https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: always # default: always
    on_failure: always # default: always
    on_start:   change # default: never
    on_cancel:  always # default: always
    on_error:   always # default: always
