name: Dependabot CI

on:
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: fastify/github-action-merge-dependabot@30c3f8f14a4f7b315ba38dbc1b793d27128fef82
        with:
          use-github-auto-merge: true
          merge-method: squash
