name: Lint
on: [push, pull_request]
env:
  CI: true

jobs:
  standard:
    name: Standard
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Lint files
        uses: goto-bus-stop/standard-action@v1
        with:
          # limit the files to lint, default '**/*.js'
          files: "{src/**/*.js,test/**/*.js}"
          # show errors in the the github diff UI
          annotate: true
        # Allow the action to add lint errors to the github diff UI
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
